# Generated by Django 2.2 on 2021-02-25 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210225_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='initials',
        ),
    ]
