# Generated by Django 2.2 on 2021-02-27 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210226_2050'),
        ('accounts', '0002_auto_20200225_1212'),
    ]

    operations = [
    ]
