# Generated by Django 3.2 on 2021-10-27 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_merge_20210227_1107'),
    ]

    operations = [
       migrations.AlterField(
           model_name='user',
           name='email',
           field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
       ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
